site_name: QIN's blog
site_url: https://qin921.github.io/
# Repository
repo_name: QIN921
repo_url: https://github.com/QIN921/QIN921.github.io/

# Copyright
copyright: Copyright &copy; QIN

#website/xxx.html style
use_directory_urls: false

# Configuration
theme:
  name: material
  custom_dir: "overrides/"
  logo: assets/logo.svg
  favicon: assets/logo.svg

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
  palette:
   # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
      - navigation.footer
      - header.autohide
  font:
    text: Roboto
    code: Ubuntu Mono, Roboto Mono

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.tables
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - https://libs.baidu.com/jquery/2.1.4/jquery.min.js
  - https://cdn.staticfile.org/webfont/1.6.28/webfontloader.js
  - javascripts/config.js
  - https://polyfill.alicdn.com/polyfill.min.js
  - https://jsd.cdn.zzko.cn/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/QIN921/
      name: github主页
    - icon: fontawesome/solid/paper-plane
      link: mailto:<zhouchuqin2002@foxmail.com>
      name: 我的邮箱
    - icon: fontawesome/solid/link
      link: https://ieeexplore.ieee.org/author/37090056269
      name: Homepage

nav:
  - 首页: index.md
  - 自我介绍: self.md
  - Studying:
    - Dive into deep learning: deep_learning/00_Dive_into_deep_learning.md
    - Image Classification: 
      - AlexNet: deep_learning/01_AlexNet.md
      - VGG: deep_learning/02_VGG.md
      - ResNet: deep_learning/03_ResNet.md
      - MobileNets: deep_learning/04_MobileNets.md
      - GoogLeNet: deep_learning/05_GoogLeNet.md
    - Object Detection: 
      - R-CNN: deep_learning/06_R-CNN.md
      - Fast R-CNN: deep_learning/07_Fast_R-CNN.md
      - Faster R-CNN: deep_learning/08_Faster_R-CNN.md
      - YOLO v1: deep_learning/09_YOLO_v1.md
      - YOLO v2: deep_learning/10_YOLOv2.md
    - Instance Segmentation:
      - U-Net: deep_learning/11_U-Net.md
      - PSPNet: deep_learning/12_PSPNet.md
      - DeepLabv3+: deep_learning/13_DeepLabv3+.md
    - Other:
      - GAN: deep_learning/14_GAN.md
      - Transformer: deep_learning/15_Transformer.md
      - Deformable Convolutional Networks: deep_learning/16_DCN.md
      - BasicVSR: deep_learning/18_RealBasicVSR.md
    - Chaos: deep_learning/17_CHAOS.md
      # - WANN：Weight Agnostic Neural Networks: deep_learning/12_WANN.md
      # - ViT：An Image is Worth 16x16 Words：Transformers for Image Recognition at Scale: deep_learning/13_Vit.md
      # - SwinT：Swin Transformer： Hierarchical Vision Transformer using Shifted Windows: deep_learning/14_SwinT.md
  - Video Compression:
    - DVC: video_compression/01_DVC.md
    - FVC: video_compression/02_FVC.md
    - NIFC: video_compression/03_NIFC.md
    - C2F: video_compression/04_C2F.md
    - CDC: video_compression/05_CDC.pdf
